CSHARP/OENIK_PROG3_2019_2_J4G2NY/Webshop.Web/Models/Location.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Webshop.Web.Models
{
    public class Location
    {
        [Display(Name = "Location ID")]
        [Required]
        [Range(0, 1000000000)]
        public decimal ID { get; set; }

        [Display(Name = "Country")]
        [Required]
        [StringLength(20)]
        public string Country { get; set; }

        [Display(Name = "Street")]
        [Required]
        [StringLength(40)]
        public string Street { get; set; }

        [Display(Name = "House_Number")]
        [Required]
        [Range(0, 10000)]
        public Nullable<decimal> House_Number { get; set; }

        [Display(Name = "Zip_Code")]
        [Required]
        public Nullable<decimal> Zip_Code { get; set; }
    }
}

CSHARP/OENIK_PROG3_2019_2_J4G2NY/Webshop.Web/Models/LocationsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Webshop.Web.Models
{
    public class LocationsViewModel
    {
        public Location EditedLocation { get; set; }
        public List<Location> ListOfLocations { get; set; }
    }
}

CSHARP/OENIK_PROG3_2019_2_J4G2NY/Webshop.Web/Controllers/LocationsController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Webshop.Logic;
using Webshop.Repository;
using Webshop.Web.Models;

namespace Webshop.Web.Controllers
{
    public class LocationsController : Controller
    {
        ILogic logic;
        IMapper mapper;
        LocationsViewModel vm;

        RepositoryHelper repoHelper;

        public LocationsController()
        {
            this.repoHelper = new RepositoryHelper(new LocRepository(), new SaleRepository(), new UserRepository());
            logic = new Logic.Logic(repoHelper);
            mapper = MapperFactory.CreateMapper();
            vm = new LocationsViewModel();
            vm.EditedLocation = new Location();
            var Locations = logic.GetAllLocations();
            vm.ListOfLocations = mapper.Map<IEnumerable<Data.Loc>, List<Models.Location>>(Locations);
        }

        private Location GetLocationModel(decimal id)
        {
            Webshop.Data.Loc oneLocation = logic.GetLocById(id);
            return mapper.Map<Data.Loc, Models.Location>(oneLocation);
        }

        // GET: Locations
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("LocationIndex", vm);
        }

        // GET: Locations/Details/5
        public ActionResult Details(decimal id)
        {
            return View("LocationDetails", GetLocationModel(id));
        }

        public ActionResult Remove(decimal id)
        {
            TempData["editResult"] = "Delete FAIL";
            if (logic.DeleteLocation(id))
            {
                TempData["editResult"] = "Delete OK";
            }
            return RedirectToAction("Index");
        }

        public ActionResult Edit(decimal id)
        {
            ViewData["editAction"] = "Edit";
            vm.EditedLocation = GetLocationModel(id);
            return View("LocationIndex", vm);
        }

        [HttpPost]
        public ActionResult Edit(Location loc, string editAction)
        {
            if (ModelState.IsValid && loc != null)
            {
                TempData["editResult"] = "Edit OK";
                if (editAction == "AddNew")
                {
                    logic.InsertLocationData(loc.ID, loc.Country, loc.Street, (decimal)loc.House_Number, (decimal)loc.Zip_Code);
                }
                else
                {
                    bool success = logic.UpdateLocation(loc.ID,
                        new Data.Loc()
                        {
                            Country = loc.Country,
                            Zip_Code = loc.Zip_Code,
                            Street = loc.Street,
                            House_Number = loc.House_Number,
                            ID = loc.ID,
                        });
                    if (!success)
                    {
                        TempData["editResult"] = "Edit Fail";
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewData["editAction"] = "Edit";
                vm.EditedLocation = loc;
                return View("LocationIndex", vm);
            }
        }
    }
}

CSHARP/OENIK_PROG3_2019_2_J4G2NY/Webshop.Web/Views/Locations/LocationDetails.cshtml
@model Webshop.Web.Models.Location
@{
    ViewBag.Title = "LocationDetails";
}

<h2>Datasheet of one Location</h2>

@Html.ActionLink("Back to the list", "Index");
<table>
    <tr>
        <td>Id for the Location</td>
        <td>@Model.ID</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Country)</td>
        <td>@Html.DisplayFor(m => m.Country)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Zip_Code)</td>
        <td>@Html.DisplayFor(m => m.Zip_Code)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Street)</td>
        <td>@Html.DisplayFor(m => m.Street)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.House_Number)</td>
        <td>@Html.DisplayFor(m => m.House_Number)</td>
    </tr>
</table>

CSHARP/OENIK_PROG3_2019_2_J4G2NY/Webshop.Web/Views/Locations/LocationEdit.cshtml
@model Webshop.Web.Models.Location

<h2>Edit one Location</h2>

@using (Html.BeginForm("Edit", "Locations"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.ID)
    @Html.Hidden("editAction", ViewData["editAction"].ToString());

    <div class="editor-label">@Html.LabelFor(m => m.Country)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Country)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Zip_Code)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Zip_Code)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Street)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Street)</div>

    <div class="editor-label">@Html.LabelFor(m => m.House_Number)</div>
    <div class="editor-field">@Html.EditorFor(m => m.House_Number)</div>

    <input type="submit" value="SEND" />
}

CSHARP/OENIK_PROG3_2019_2_J4G2NY/Webshop.Web/Views/Locations/LocationIndex.cshtml
@model Webshop.Web.Models.LocationsViewModel
@{
    ViewBag.Title = "Crud Index";
}

<h2>Locations Index</h2>

<p style="color:red; font-weight: bold">@TempData["editResult"]</p>

@Html.Partial("LocationEdit", Model.EditedLocation)
@Html.Partial("LocationList", Model.ListOfLocations)

CSHARP/OENIK_PROG3_2019_2_J4G2NY/Webshop.Web/Views/Locations/LocationList.cshtml
@model IEnumerable<Webshop.Web.Models.Location>

@{
    ViewBag.Title = "LocationsList";
}

<h2>List of locations</h2>

@if (Model.Count() == 0)
{
    <h2>No data in the database</h2>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().Street)</th>
            <th>@Html.DisplayNameFor(m => m.First().House_Number)</th>
            <th>Datasheet</th>
            <th>Delete</th>
            <th>Edit</th>
        </tr>
        <@foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m => item.Street)</td>
                <td>@Html.DisplayFor(m => item.House_Number.ToString())</td>
                <td>@Html.ActionLink("[SHOW]", "Details", new { id = item.ID })</td>
                <td>@Html.ActionLink("[DEL]", "Remove", new { id = item.ID })</td>
                <td>@Html.ActionLink("[EDIT]", "Edit", new { id = item.ID })</td>
            </tr>
        }
    </table>
}